# Generated by Django 3.2 on 2022-01-18 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('number', models.CharField(max_length=11, null=True, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('passwrd', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fname', 'lname'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('number', models.CharField(max_length=11, null=True, unique=True)),
                ('message', models.CharField(blank=True, max_length=1000, null=True)),
                ('recdate', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.siteuser')),
            ],
            options={
                'ordering': ['-recdate'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('treatment', models.CharField(choices=[('physical_therapy', 'Physical Therapy -£45'), ('sports_massage_therapy', 'Sports Massage Therapy -£45'), ('fire_cupping_therapy', 'Fire Cupping Therapy -£50'), ('swedish_massage_therapy', 'Swedish Massage Therapy -£45'), ('aroma_therapy', 'Aromatherapy -£45'), ('wet_cupping_therapy', 'Wet Cupping Therapy -£45'), ('graston_therapy', 'Graston IATM Therapy -£45'), ('nutrition_therapy', 'Nutritional Therapy -£45')], default='Physical Therapy -£45', max_length=100)),
                ('date', models.DateField(null=True)),
                ('sent_date', models.DateField(auto_now_add=True)),
                ('time', models.CharField(choices=[('08:00-09:00', '08:00 to 09:00'), ('09:00-10:00', '09:00 to 10:00'), ('10:00-11:00', '10:00 to 11:00'), ('11:00-12:00', '11:00 to 12:00'), ('12:00-13:00', '12:00 to 13:00'), ('13:00-14:00', '13:00 to 14:00'), ('14:00-15:00', '14:00 to 15:00'), ('15:00-16:00', '15:00 to 16:00'), ('16:00-17:00', '16:00 to 17:00')], default='08:00-09:00', max_length=50)),
                ('accepted', models.BooleanField(default=False)),
                ('addinfo', models.TextField(blank=True, max_length=1000, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainsite.siteuser')),
            ],
            options={
                'ordering': ['-sent_date'],
            },
        ),
    ]
