# Generated by Django 3.2 on 2022-01-19 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='number',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='number',
        ),
        migrations.RemoveField(
            model_name='siteuser',
            name='passwrd',
        ),
        migrations.AddField(
            model_name='message',
            name='pnumber',
            field=models.CharField(default='', max_length=11, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='siteuser',
            name='pnumber',
            field=models.CharField(default='', max_length=11),
            preserve_default=False,
        ),
    ]
