# Generated by Django 3.2 on 2022-01-17 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_auto_20220117_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['fname', 'lname']},
        ),
        migrations.AlterField(
            model_name='booking',
            name='treatment',
            field=models.CharField(choices=[('Physical Therapy', 'Physical Therapy -£45'), ('Sports Massage Therapy', 'Sports Massage Therapy -£45'), ('Fire Cupping Therapy', 'Fire Cupping Therapy -£50'), ('Swedish Massage Therapy', 'Swedish Massage Therapy -£45'), ('Aromatherapy', 'Aromatherapy -£45'), ('Wet Cupping Therapy', 'Wet Cupping Therapy -£45'), ('Graston Therapy', 'Graston IATM Therapy -£45'), ('Nutrition Therapy', 'Nutritional Therapy -£45')], default='Physical Therapy -£45', max_length=100),
        ),
    ]
