# Generated by Django 3.2 on 2022-01-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0006_alter_message_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(default='no message', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='pnumber',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
