# Generated by Django 3.2 on 2022-01-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0008_auto_20220117_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='number',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
