# Generated by Django 3.2 on 2022-01-17 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mainsite', '0010_siteuser_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-recdate']},
        ),
        migrations.AlterModelOptions(
            name='siteuser',
            options={'ordering': ['-fname', 'lname']},
        ),
        migrations.AddField(
            model_name='client',
            name='recdate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='siteuser',
            name='number',
            field=models.CharField(max_length=11, null=True, unique=True),
        ),
    ]
